language: python
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"
  # - "3.6"      
  - "3.7"
  - "3.8"
  - "3.8.3"  # current default Python on Travis CI
  - "nightly"  # nightly build, which points to a recent development version of CPython build.
# jobs:
#   include:
#     - python: '3.8.3' # this is not strictly necessary
#       env: EXTRA_TESTS=true
#     - python: '3.7'
#       env: EXTRA_TESTS=true
# script: env $EXTRA_TESTS ./test.py $TEST_SUITE
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cd chatbot
  - python manage.py migrate
  - python manage.py runserver